# Generated by Django 5.1.4 on 2024-12-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Shifokor', 'verbose_name_plural': 'Shifokorlar'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='turn',
            options={'verbose_name': 'Navbat', 'verbose_name_plural': 'Navbatlar'},
        ),
        migrations.RenameField(
            model_name='turn',
            old_name='total',
            new_name='price',
        ),
    ]
