# Generated by Django 5.1.4 on 2024-12-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_doctor_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-id'], 'verbose_name': 'Shifokor', 'verbose_name_plural': 'Shifokorlar'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-id'], 'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='turn',
            options={'ordering': ['-created_at'], 'verbose_name': 'Navbat', 'verbose_name_plural': 'Navbatlar'},
        ),
        migrations.AddField(
            model_name='turn',
            name='turn_type',
            field=models.CharField(choices=[('0', 'Doctor'), ('1', 'Service')], default='0', max_length=10),
        ),
    ]
